### ISSUE TITLE
Possible bug related to XC gradients in serial and mpi versions

### ISSUE THREAD

**Issue by Madu86** [merzlab/QUICK#75]
DFT gradients between cuda/cudampi and serial/mpi versions are significantly different for some molecules. For example, the following differences are observed for morphine B3LYP/6-31G test case. 

Serial/MPI version:

   39X    -3.1557002410     0.0103348688
   39Y    -2.6446002020     0.0002881292
   39Z     0.6672000509    -0.0120197547
   40X    -3.8483002939     0.0091268736
   40Y     1.0686000816     0.0105647101
   40Z     1.1031000842    -0.0082148827

CUDA/CUDAMPI version:

   39X    -3.1557002410     0.1090530496
   39Y    -2.6446002020     0.0338787728
   39Z     0.6672000509    -0.2400229409
   40X    -3.8483002939     0.0763664437
   40Y     1.0686000816     0.2128912033
   40Z     1.1031000842    -0.1546795715

This is possibly coming from the host code computing grid weight derivatives.

**Comment by agoetz** [comment]
@madu Is this still relevant? I just executed `grad_daspi_meoh_b3lyp_6-31g.in` with `quick.cuda` and `mpirun -np 16 quick.MPI` and I get gradients and point charge gradients that differ by less than 1e-6. Please close this issue if you have no further concerns.

**Comment by Madu86** [comment]
Probably we have fixed this with recent improvements. Can you please confirm with this input?

```
DFT BLYP BASIS=6-31G CUTOFF=1.0d-9 DENSERMS=1.0d-8 GRADIENT
  
 O         -1.99300       -0.47400        1.20050
 O         -2.78260       -2.51680       -0.22180
 O         -3.62200        1.84210        0.55790
 N          3.17770       -0.01010        0.44740
 C          0.36990       -0.71490        0.66160
 C          1.29130       -1.30460       -0.41700
 C          2.34410       -0.20230       -0.76400
 C         -0.93770       -1.47500        0.98480
 C          1.19880       -0.39070        1.92010
 C         -0.25160        0.53020        0.12050
 C          1.68870        1.10520       -1.32790
 C          2.43150        0.47540        1.61260
 C          0.33840        1.43060       -0.74800
 C         -1.36310       -2.50670       -0.09240
 C          0.50660       -1.81830       -1.59710
 C         -1.56720        0.63060        0.51360
 C         -0.71550       -2.34920       -1.44250
 C          4.37330        0.79160        0.20840
 C         -0.41840        2.54150       -1.12460
 C         -2.33100        1.72170        0.16200
 C         -1.73820        2.69360       -0.65410
 H          1.82780       -2.17590       -0.01180
 H          3.00290       -0.60350       -1.54650
 H         -0.84510       -2.01280        1.93730
 H          1.53660       -1.33350        2.37120
 H          0.58990        0.11740        2.67900
 H          1.54740        0.95960       -2.40750
 H          2.35300        1.96800       -1.21940
 H          2.12710        1.52050        1.47600
 H          3.08010        0.45840        2.49750
 H         -1.07720       -3.50670        0.25930
 H          0.96010       -1.79470       -2.58310
 H         -1.23000       -2.75050       -2.31090
 H          4.15000        1.84790        0.02870
 H          4.93800        0.40550       -0.64720
 H          5.04440        0.73520        1.07300
 H         -0.00620        3.28240       -1.80430
 H         -2.31210        3.56380       -0.96450
 H         -3.15570       -2.64460        0.66720
 H         -3.84830        1.06860        1.10310

```

**Comment by agoetz** [comment]
Still a problem. Gradients are spectacularly different between CPU MPI and CUDA serial versions. I noticed the CUDA code takes less iterations to converge. 34 vs 51. You can reduce DENSERMS from 1e-8 to 1e-6 to get pretty similar (differing between CUDA/MPI) version but within 18 / 16 cycles.

**Comment by agoetz** [comment]
This is what I got for gradinets
```
head tst-cuda-grad.out tst-mpi-16-grad.out 
==> tst-cuda-grad.out <==

 ANALYTICAL GRADIENT: 
----------------------------------------
 COORDINATE    XYZ            GRADIENT
----------------------------------------
    1X    -1.9930001522     0.1965944842
    1Y    -0.4740000362     0.0991425239
    1Z     1.2005000917    -0.1732620030
    2X    -2.7826002125     0.0815820377
    2Y    -2.5168001922    -0.0055278892

==> tst-mpi-16-grad.out <==

 ANALYTICAL GRADIENT: 
----------------------------------------
 COORDINATE    XYZ            GRADIENT
----------------------------------------
    1X    -1.9930001522     0.0212762904
    1Y    -0.4740000362     0.0127520291
    1Z     1.2005000917    -0.0206340815
    2X    -2.7826002125     0.0221831544
    2Y    -2.5168001922     0.0005953827
```

**Comment by Madu86** [comment]
@agoetz Thanks. I will investigate this tomorrow. Have to check HF vs B3LYP first. My wild guess is ssweder device kernel.

**Comment by Madu86** [comment]
@agoetz The problem is that we are using 1.0e-10 as threshold here: https://github.com/merzlab/QUICK/blob/master/src/gradient.f90#L947, and 1.0e-9 in CUDA code. When we set this value to 1.0e-10 in CUDA code, we get correct gradients for Morphine B3LYP/6-31G example that agrees well with serial version and reference code.  

Energy:
```
        Ref                                     Serial.                            Cuda
-939.338829054        -939.338672447         -939.338672669 
```

Grad:
```
 Ref(Force)     Serial (Grad)            Cuda (Grad) 
-0.00937	 0.0093682870	 0.0093682246
-0.01200	 0.0115526670	 0.0115526305
 0.01355	-0.0134237848	-0.0134237240
-0.01472	 0.0145936437	 0.0145935985
-0.00192	 0.0019470262	 0.0019470165
-0.01113	 0.0110226938	 0.0110227328
-0.02417	 0.0240763892	 0.0240763190
 0.00409	-0.0040967748	-0.0040967671
 0.00721	-0.0071526708	-0.0071526504
 0.00348	-0.0034595267	-0.0034595464
-0.00123	 0.0011651444	 0.0011651506
-0.00264	 0.0025412030	 0.0025412106
-0.00689	 0.0068555153	 0.0068555182
 0.00556	-0.0055084250	-0.0055084374
 0.00285	-0.0029458313	-0.0029458352
 0.00200	-0.0020398117	-0.0020397865
-0.00456	 0.0044321708	 0.0044321199
-0.00763	 0.0074228522	 0.0074228755
-0.00272	 0.0024819631	 0.0024819882
-0.00451	 0.0045222493	 0.0045222011
 0.00192	-0.0018515202	-0.0018515930
 0.01627	-0.0163304807	-0.0163304766
-0.03344	 0.0336481044	 0.0336480295
 0.01717	-0.0174090973	-0.0174090498
 0.00623	-0.0060582928	-0.0060583058
-0.00493	 0.0051128066	 0.0051127869
 0.00691	-0.0071015248	-0.0071014983
 0.00370	-0.0035516590	-0.0035515376
 0.01152	-0.0116683952	-0.0116683026
-0.01123	 0.0113370087	 0.0113369751
-0.00127	 0.0012541584	 0.0012541772
-0.00494	 0.0048508344	 0.0048508645
-0.00441	 0.0046706927	 0.0046706528
-0.00550	 0.0054230765	 0.0054230845
-0.00280	 0.0027245074	 0.0027245512
 0.00651	-0.0063997924	-0.0063997354
 0.00316	-0.0031154676	-0.0031155616
-0.00052	 0.0005256753	 0.0005256917
 0.00350	-0.0036116821	-0.0036116761
 0.00661	-0.0064139493	-0.0064139027
-0.00433	 0.0046189506	 0.0046189370
-0.00625	 0.0063227745	 0.0063228244
-0.00645	 0.0064033944	 0.0064034609
 0.00003	-0.0000040454	-0.0000040246
 0.00171	-0.0016783533	-0.0016783957
 0.01395	-0.0139485983	-0.0139486402
 0.01999	-0.0197933247	-0.0197933228
-0.01234	 0.0122335560	 0.0122334986
 0.00228	-0.0022447921	-0.0022447961
 0.00706	-0.0070396087	-0.0070396298
-0.00485	 0.0049193386	 0.0049192935
 0.00953	-0.0095874857	-0.0095874089
-0.00509	 0.0049684559	 0.0049684935
 0.00134	-0.0012386873	-0.0012386966
-0.01279	 0.0128386343	 0.0128386752
 0.00577	-0.0058147117	-0.0058147262
 0.00113	-0.0011377148	-0.0011376959
 0.01492	-0.0149000667	-0.0149000454
 0.00781	-0.0077576180	-0.0077575980
-0.01057	 0.0106197372	 0.0106197501
 0.00791	-0.0078630057	-0.0078629910
 0.00666	-0.0066708234	-0.0066707847
-0.00673	 0.0067513463	 0.0067513025
 0.00592	-0.0058822649	-0.0058822693
 0.00438	-0.0044224887	-0.0044224832
 0.00338	-0.0033649688	-0.0033649835
 0.00118	-0.0011207994	-0.0011207997
 0.00061	-0.0006196297	-0.0006196246
 0.00225	-0.0023141300	-0.0023141065
-0.00254	 0.0025517299	 0.0025517099
 0.00289	-0.0029787421	-0.0029787377
 0.00016	-0.0001082676	-0.0001082830
 0.00050	-0.0004249216	-0.0004249180
-0.00169	 0.0015989935	 0.0015989982
-0.00079	 0.0008255020	 0.0008255074
-0.00179	 0.0017841778	 0.0017841788
 0.00014	-0.0001237824	-0.0001237822
-0.00225	 0.0022931334	 0.0022931389
 0.00239	-0.0023911636	-0.0023911566
 0.00102	-0.0010098183	-0.0010098158
-0.00191	 0.0019003417	 0.0019003579
 0.00512	-0.0051592011	-0.0051592000
-0.00142	 0.0014627366	 0.0014627335
-0.00041	 0.0004141067	 0.0004141024
-0.00308	 0.0029875534	 0.0029875644
 0.00618	-0.0061482670	-0.0061482825
-0.00033	 0.0001509206	 0.0001509120
 0.00295	-0.0029155353	-0.0029155342
-0.00020	 0.0001724228	 0.0001724157
-0.00245	 0.0024971887	 0.0024971774
 0.00734	-0.0073045210	-0.0073045405
-0.00236	 0.0022590052	 0.0022590176
 0.00603	-0.0059893436	-0.0059893598
 0.00209	-0.0021045961	-0.0021046135
 0.00096	-0.0009674379	-0.0009674422
-0.00080	 0.0007604202	 0.0007604379
-0.00499	 0.0049796371	 0.0049796203
-0.00115	 0.0011330972	 0.0011330871
 0.00373	-0.0037743190	-0.0037743404
 0.00053	-0.0005586910	-0.0005587003
 0.00767	-0.0076226126	-0.0076226220
-0.00155	 0.0015223216	 0.0015223256
-0.00252	 0.0025635308	 0.0025635284
-0.00063	 0.0006272995	 0.0006272950
-0.00123	 0.0012580322	 0.0012580365
-0.00181	 0.0017976709	 0.0017976673
 0.00006	-0.0000454886	-0.0000454933
 0.00161	-0.0016238023	-0.0016238035
-0.00061	 0.0006154328	 0.0006154202
-0.00001	 0.0000027572	 0.0000027537
 0.00042	-0.0004485663	-0.0004485631
-0.00180	 0.0017580764	 0.0017580703
-0.00350	 0.0035674790	 0.0035674913
 0.00283	-0.0028126821	-0.0028126863
-0.00732	 0.0072928190	 0.0072928003
 0.00137	-0.0014127682	-0.0014127653
 0.00251	-0.0023130058	-0.0023130159
-0.00772	 0.0076517926	 0.0076517772
-0.00256	 0.0023879710	 0.0023879690
 0.00277	-0.0027100470	-0.0027100414

```

**Comment by agoetz** [comment]
>The problem is that we are using 1.0e-10 as threshold here: https://github.com/merzlab/QUICK/blob/master/src/gradient.f90#L947, and 1.0e-9 in CUDA code. When we set this value to 1.0e-10 in CUDA code, we get correct gradients for Morphine B3LYP/6-31G example that agrees well with serial version and reference code.

I am confused. I thought difference was between serial and MPI:
(serial = cuda) /= (MPI = cuda.MPI)

**Comment by Madu86** [comment]
> DFT gradients between cuda/cudampi and serial/mpi versions are significantly different for some molecules. For example, the following differences are observed for morphine B3LYP/6-31G test case.
> 
> Serial/MPI version:
> 
> 39X -3.1557002410 0.0103348688
> 39Y -2.6446002020 0.0002881292
> 39Z 0.6672000509 -0.0120197547
> 40X -3.8483002939 0.0091268736
> 40Y 1.0686000816 0.0105647101
> 40Z 1.1031000842 -0.0082148827
> 
> CUDA/CUDAMPI version:
> 
> 39X -3.1557002410 0.1090530496
> 39Y -2.6446002020 0.0338787728
> 39Z 0.6672000509 -0.2400229409
> 40X -3.8483002939 0.0763664437
> 40Y 1.0686000816 0.2128912033
> 40Z 1.1031000842 -0.1546795715
> 

The original issue is between cpu and CUDA versions. Checking serial vs mpi now.

**Comment by Madu86** [comment]
@agoetz Yes, that cutoff was the problem. 

```
Ref(Force)     Serial (Grad)            Cuda (Grad)          MPI(4 cores)         CUDAMPI(4 GPUs)
-0.00937	 0.0093682870	 0.0093682246	 0.0093682870	 0.0093682243
-0.01200	 0.0115526670	 0.0115526305	 0.0115526670	 0.0115526306
 0.01355	-0.0134237848	-0.0134237240	-0.0134237848	-0.0134237240
-0.01472	 0.0145936437	 0.0145935985	 0.0145936437	 0.0145935987
-0.00192	 0.0019470262	 0.0019470165	 0.0019470262	 0.0019470165
-0.01113	 0.0110226938	 0.0110227328	 0.0110226938	 0.0110227327
-0.02417	 0.0240763892	 0.0240763190	 0.0240763892	 0.0240763190
 0.00409	-0.0040967748	-0.0040967671	-0.0040967748	-0.0040967669
 0.00721	-0.0071526708	-0.0071526504	-0.0071526708	-0.0071526505
 0.00348	-0.0034595267	-0.0034595464	-0.0034595267	-0.0034595462
-0.00123	 0.0011651444	 0.0011651506	 0.0011651443	 0.0011651507
-0.00264	 0.0025412030	 0.0025412106	 0.0025412029	 0.0025412107
-0.00689	 0.0068555153	 0.0068555182	 0.0068555153	 0.0068555181
 0.00556	-0.0055084250	-0.0055084374	-0.0055084250	-0.0055084375
 0.00285	-0.0029458313	-0.0029458352	-0.0029458313	-0.0029458350
 0.00200	-0.0020398117	-0.0020397865	-0.0020398117	-0.0020397864
-0.00456	 0.0044321708	 0.0044321199	 0.0044321708	 0.0044321199
-0.00763	 0.0074228522	 0.0074228755	 0.0074228522	 0.0074228756
-0.00272	 0.0024819631	 0.0024819882	 0.0024819631	 0.0024819882
-0.00451	 0.0045222493	 0.0045222011	 0.0045222493	 0.0045222012
 0.00192	-0.0018515202	-0.0018515930	-0.0018515203	-0.0018515928
 0.01627	-0.0163304807	-0.0163304766	-0.0163304807	-0.0163304763
-0.03344	 0.0336481044	 0.0336480295	 0.0336481044	 0.0336480295
 0.01717	-0.0174090973	-0.0174090498	-0.0174090973	-0.0174090498
 0.00623	-0.0060582928	-0.0060583058	-0.0060582928	-0.0060583058
-0.00493	 0.0051128066	 0.0051127869	 0.0051128066	 0.0051127869
 0.00691	-0.0071015248	-0.0071014983	-0.0071015248	-0.0071014986
 0.00370	-0.0035516590	-0.0035515376	-0.0035516590	-0.0035515371
 0.01152	-0.0116683952	-0.0116683026	-0.0116683951	-0.0116683031
-0.01123	 0.0113370087	 0.0113369751	 0.0113370087	 0.0113369753
-0.00127	 0.0012541584	 0.0012541772	 0.0012541584	 0.0012541774
-0.00494	 0.0048508344	 0.0048508645	 0.0048508344	 0.0048508644
-0.00441	 0.0046706927	 0.0046706528	 0.0046706927	 0.0046706528
-0.00550	 0.0054230765	 0.0054230845	 0.0054230765	 0.0054230844
-0.00280	 0.0027245074	 0.0027245512	 0.0027245074	 0.0027245512
 0.00651	-0.0063997924	-0.0063997354	-0.0063997924	-0.0063997355
 0.00316	-0.0031154676	-0.0031155616	-0.0031154676	-0.0031155614
-0.00052	 0.0005256753	 0.0005256917	 0.0005256753	 0.0005256919
 0.00350	-0.0036116821	-0.0036116761	-0.0036116821	-0.0036116764
 0.00661	-0.0064139493	-0.0064139027	-0.0064139493	-0.0064139029
-0.00433	 0.0046189506	 0.0046189370	 0.0046189506	 0.0046189369
-0.00625	 0.0063227745	 0.0063228244	 0.0063227745	 0.0063228242
-0.00645	 0.0064033944	 0.0064034609	 0.0064033944	 0.0064034608
 0.00003	-0.0000040454	-0.0000040246	-0.0000040454	-0.0000040246
 0.00171	-0.0016783533	-0.0016783957	-0.0016783533	-0.0016783956
 0.01395	-0.0139485983	-0.0139486402	-0.0139485983	-0.0139486402
 0.01999	-0.0197933247	-0.0197933228	-0.0197933247	-0.0197933230
-0.01234	 0.0122335560	 0.0122334986	 0.0122335560	 0.0122334988
 0.00228	-0.0022447921	-0.0022447961	-0.0022447921	-0.0022447965
 0.00706	-0.0070396087	-0.0070396298	-0.0070396087	-0.0070396299
-0.00485	 0.0049193386	 0.0049192935	 0.0049193385	 0.0049192936
 0.00953	-0.0095874857	-0.0095874089	-0.0095874857	-0.0095874090
-0.00509	 0.0049684559	 0.0049684935	 0.0049684559	 0.0049684935
 0.00134	-0.0012386873	-0.0012386966	-0.0012386873	-0.0012386966
-0.01279	 0.0128386343	 0.0128386752	 0.0128386343	 0.0128386751
 0.00577	-0.0058147117	-0.0058147262	-0.0058147117	-0.0058147259
 0.00113	-0.0011377148	-0.0011376959	-0.0011377148	-0.0011376959
 0.01492	-0.0149000667	-0.0149000454	-0.0149000667	-0.0149000457
 0.00781	-0.0077576180	-0.0077575980	-0.0077576180	-0.0077575982
-0.01057	 0.0106197372	 0.0106197501	 0.0106197372	 0.0106197502
 0.00791	-0.0078630057	-0.0078629910	-0.0078630057	-0.0078629910
 0.00666	-0.0066708234	-0.0066707847	-0.0066708234	-0.0066707846
-0.00673	 0.0067513463	 0.0067513025	 0.0067513463	 0.0067513024
 0.00592	-0.0058822649	-0.0058822693	-0.0058822649	-0.0058822693
 0.00438	-0.0044224887	-0.0044224832	-0.0044224887	-0.0044224832
 0.00338	-0.0033649688	-0.0033649835	-0.0033649688	-0.0033649835
 0.00118	-0.0011207994	-0.0011207997	-0.0011207994	-0.0011207998
 0.00061	-0.0006196297	-0.0006196246	-0.0006196297	-0.0006196246
 0.00225	-0.0023141300	-0.0023141065	-0.0023141300	-0.0023141065
-0.00254	 0.0025517299	 0.0025517099	 0.0025517299	 0.0025517099
 0.00289	-0.0029787421	-0.0029787377	-0.0029787421	-0.0029787377
 0.00016	-0.0001082676	-0.0001082830	-0.0001082676	-0.0001082830
 0.00050	-0.0004249216	-0.0004249180	-0.0004249216	-0.0004249180
-0.00169	 0.0015989935	 0.0015989982	 0.0015989935	 0.0015989982
-0.00079	 0.0008255020	 0.0008255074	 0.0008255020	 0.0008255075
-0.00179	 0.0017841778	 0.0017841788	 0.0017841778	 0.0017841787
 0.00014	-0.0001237824	-0.0001237822	-0.0001237824	-0.0001237822
-0.00225	 0.0022931334	 0.0022931389	 0.0022931334	 0.0022931389
 0.00239	-0.0023911636	-0.0023911566	-0.0023911636	-0.0023911566
 0.00102	-0.0010098183	-0.0010098158	-0.0010098183	-0.0010098159
-0.00191	 0.0019003417	 0.0019003579	 0.0019003417	 0.0019003578
 0.00512	-0.0051592011	-0.0051592000	-0.0051592011	-0.0051592000
-0.00142	 0.0014627366	 0.0014627335	 0.0014627366	 0.0014627335
-0.00041	 0.0004141067	 0.0004141024	 0.0004141067	 0.0004141025
-0.00308	 0.0029875534	 0.0029875644	 0.0029875534	 0.0029875644
 0.00618	-0.0061482670	-0.0061482825	-0.0061482670	-0.0061482824
-0.00033	 0.0001509206	 0.0001509120	 0.0001509206	 0.0001509119
 0.00295	-0.0029155353	-0.0029155342	-0.0029155353	-0.0029155342
-0.00020	 0.0001724228	 0.0001724157	 0.0001724228	 0.0001724157
-0.00245	 0.0024971887	 0.0024971774	 0.0024971887	 0.0024971774
 0.00734	-0.0073045210	-0.0073045405	-0.0073045210	-0.0073045404
-0.00236	 0.0022590052	 0.0022590176	 0.0022590052	 0.0022590177
 0.00603	-0.0059893436	-0.0059893598	-0.0059893436	-0.0059893598
 0.00209	-0.0021045961	-0.0021046135	-0.0021045961	-0.0021046134
 0.00096	-0.0009674379	-0.0009674422	-0.0009674379	-0.0009674422
-0.00080	 0.0007604202	 0.0007604379	 0.0007604202	 0.0007604378
-0.00499	 0.0049796371	 0.0049796203	 0.0049796371	 0.0049796204
-0.00115	 0.0011330972	 0.0011330871	 0.0011330972	 0.0011330872
 0.00373	-0.0037743190	-0.0037743404	-0.0037743190	-0.0037743403
 0.00053	-0.0005586910	-0.0005587003	-0.0005586910	-0.0005587003
 0.00767	-0.0076226126	-0.0076226220	-0.0076226127	-0.0076226221
-0.00155	 0.0015223216	 0.0015223256	 0.0015223216	 0.0015223256
-0.00252	 0.0025635308	 0.0025635284	 0.0025635308	 0.0025635284
-0.00063	 0.0006272995	 0.0006272950	 0.0006272995	 0.0006272950
-0.00123	 0.0012580322	 0.0012580365	 0.0012580322	 0.0012580365
-0.00181	 0.0017976709	 0.0017976673	 0.0017976709	 0.0017976673
 0.00006	-0.0000454886	-0.0000454933	-0.0000454886	-0.0000454933
 0.00161	-0.0016238023	-0.0016238035	-0.0016238023	-0.0016238035
-0.00061	 0.0006154328	 0.0006154202	 0.0006154328	 0.0006154202
-0.00001	 0.0000027572	 0.0000027537	 0.0000027572	 0.0000027536
 0.00042	-0.0004485663	-0.0004485631	-0.0004485663	-0.0004485631
-0.00180	 0.0017580764	 0.0017580703	 0.0017580764	 0.0017580704
-0.00350	 0.0035674790	 0.0035674913	 0.0035674790	 0.0035674914
 0.00283	-0.0028126821	-0.0028126863	-0.0028126821	-0.0028126862
-0.00732	 0.0072928190	 0.0072928003	 0.0072928190	 0.0072928003
 0.00137	-0.0014127682	-0.0014127653	-0.0014127682	-0.0014127654
 0.00251	-0.0023130058	-0.0023130159	-0.0023130058	-0.0023130158
-0.00772	 0.0076517926	 0.0076517772	 0.0076517926	 0.0076517773
-0.00256	 0.0023879710	 0.0023879690	 0.0023879710	 0.0023879689
 0.00277	-0.0027100470	-0.0027100414	-0.0027100470	-0.0027100414


```

**Comment by agoetz** [comment]
OK, great that you found it! How come that the cutoff is different?

**Comment by Madu86** [comment]
@agoetz Sometime ago I noticed an occasional weird behavior happening in XC gradients but couldn't figure out what's going on. So I set the DMCutoff in CUDA code to 1.0e-9: https://github.com/merzlab/QUICK/blob/master/src/cuda/gpu.cu#L416 and everything looked good. What I didn't realize was that in the serial code its actually set to 1.0e-10 not e-9. So when I revisited this problem today, I was curious why I cannot pass the value of DMCutoff from f90 to C side correctly. After looking out for extraterrestrial reasons, I finally checked the C function call in the f90 code: https://github.com/merzlab/QUICK/blob/master/src/gradient.f90#L646. Its a stupid parameter leak and the bloody compiler never complained!!!

**Comment by agoetz** [comment]
Hm. So in the end it was not a serial/MPI error. Any idea why this does not pose a problem for other tests?

**Comment by Madu86** [comment]
I think it depends on the shape of the molecule and the basis set we choose. If there are many gird points with densities eliminated by 10-9 cutoff but retains with 10-10, this can happen, right? So I think this example was an extreme case.

**Comment by agoetz** [comment]
Yes that makes sense. Thanks Madu.
